---
title: "Data Analysis Using R"
author: "David Mawdsley"
output: 
  revealjs::revealjs_presentation:
    center: false
    transition: fade
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
## Data Analysis Using R
<style type="text/css">
p { text-align: left; }
</style>

Initial tasks:

1. Log into a PC (or have your laptop ready to use)
2. Check you can load RStudio
3. Open the course notes page at [https://UoMResearchIT.github.io/r-tidyverse-intro/](https://UoMResearchIT.github.io/r-tidyverse-intro/)
  * There is a link to this slideshow there
4. There is no sign-in sheet.  Attendance is recorded via the feedback form [http://bit.ly/2xP95Ef](http://bit.ly/2xP95Ef)

## Introduction

* Aims of the day
* Research IT
* Teaching methods


## Housekeeping

* Fire exit
* Toilets
* Coffee breaks and lunch
* Course timing
* Feedback ([form](http://bit.ly/2xP95Ef) and verbal)

## Aims of the day

* Introduction to R
  + No prior knowledge of R assumed
  + Focus on using R for analysis rather than programming
* Does not teach statistics
* The aim is to teach you enough know how to find out more

## Research IT
Described on the [IT Services website](http://www.itservices.manchester.ac.uk/research/)

Announcements given via the [Research IT blog](https://researchitnews.org/) and newsletter (signup via the blog page) and on Twitter [@﻿UoM_eResearch](http://twitter.com/uom_eresearch)

* [Training courses](http://ri.itservices.manchester.ac.uk/training) teach computing skills for research
* Advice and guidance about research software
* Access to specialist support and consultancy e.g. code reviews
* Access to HPC systems - where you can run R.
* [Full list of services on offer](http://www.itservices.manchester.ac.uk/research/services/)

Get in touch via the [support centre](http://supportcentre.manchester.ac.uk/)


## Why learn R?

* (probably) the most popular language for data-analysis and statistics
* It's free
* It's extensible
    + Interactive apps [Shiny](https://shiny.rstudio.com/), e.g. [gapminder visualisation](https://shinyapp.mawds.co.uk/app/worked_example)
    + Reproducible research with [Knitr](https://yihui.name/knitr/)
    + [Presentations](https://www.r-bloggers.com/creating-a-presentation-with-r/)
* Over 13,000 packages  
    + This does mean there's (often) more than one way to do a task

## R user groups

R user groups are a great way of finding out more about R.  

* [University of Manchester R user group](https://rumgroup.github.io/Home/)
    + Meets monthly
    + [Email list](https://listserv.manchester.ac.uk/cgi-bin/wa?A0=RUM) for announcements, questions etc.
    + Has tea, coffee and biscuits
    + Separate beginners' group
* [ManchesterR](http://www.rmanchester.org/)
    + City-wide group (not affiliated with the university)
    + Meets quarterly 
    + Typically 3-4 presentations; often a commercial focus.
  
## Teaching methods

* The course is based on the [Software Carpentry](https://software-carpentry.org) [R for reproducible scientific research](http://swcarpentry.github.io/r-novice-gapminder/) course
    + Abridged
    + Doesn't cover version control, but we offer [a separate course on this](http://app.manchester.ac.uk/rgit)
    + Teaches the [tidyverse](http://tidyverse.org); "an ecosystem of packages designed with common APIs and a shared philosophy"
    
## Teaching methods

* The course is _interactive_
    + These are the only slides
* Getting help
    + The sticky notes 
* Course notes
    + Try to type-along without the notes
    + All the code is in the notes (Extras menu); you can cut and paste this into RStudio.
    + The slides will remain online after the course.

##  Let's get started

https://uomresearchit.github.io/r-tidyverse-intro/
